###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: laravel-docker-mysql
      working_dir: /application
      tty: true
      restart: unless-stopped
      volumes:
        - ./src:/application
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=rootpass
        - MYSQL_DATABASE=laraveldb
        - MYSQL_USER=laraveluser
        - MYSQL_PASSWORD=laravelpass
        - SERVICE_TAGS:dev
        - SERVICE_NAME:mysql
      ports:
        - "8890:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-docker-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: laravel-docker-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

